homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('message/', views.message, name='message'),
]

story/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.
class ClassYear(models.Model):
    class_year = models.IntegerField()

    def __str__(self):
        return str(self.class_year)

class Friends(models.Model):
    display_name = models.CharField(max_length=30, default='anonymous')
    hobby = models.CharField(max_length=30, default='no hobby')
    favourite_food = models.CharField(max_length=30, default='no favourite')
    class_year = models.ForeignKey(ClassYear, on_delete=models.CASCADE)

    def __str__(self):
        return self.display_name

homepage/forms.py
from django import forms
from .models import Friends, ClassYear

class input(forms.Form):
    display_name = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Input your name',
        'type' : 'text',
        'maxlength' : '50',
        'required' : True,
        'style' : 'border:0; width:100%;text-align:center;background:black;color:white;',
        'label' : 'Name',
    }))
    hobby = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Input your hobby',
        'type' : 'text',
        'maxlength' : '50',
        'required' : True,
        'style' : 'border:0; width:100%;text-align:center;background:black;color:white;',
        'label' : 'Hobby',
    }))
    favourite_food = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Input your favourite food or drinks',
        'type' : 'text',
        'maxlength' : '50',
        'required' : True,
        'style' : 'border:0; width:100%;text-align:center;background:black;color:white;',
        'label' : 'Favourite food or drinks',
    }))
    class_year = forms.ModelChoiceField(queryset=ClassYear.objects.all())

# class input(forms.ModelForm):
#     class Meta:
#         model = Friends
#         fields = ['display_name', 'hobby', 'favourite_food', 'class_year']

#         widgets = {
#             'display_name' : forms.TextInput(attrs={
#                 'class' : 'form-control',
#                 'placeholder' : 'Input your name',
#                 'type' : 'text',
#                 'maxlength' : '50',
#                 'required' : True,
#                 'style' : 'border:0; width:100%;text-align:center;background:black;color:white;',
#                 'label' : 'Name',
#                 }),
#             'hobby' : forms.TextInput(attrs={
#                 'class' : 'form-control',
#                 'placeholder' : 'Input your hobby',
#                 'type' : 'text',
#                 'maxlength' : '50',
#                 'required' : True,
#                 'style' : 'border:0; width:100%;text-align:center;background:black;color:white;',
#                 'label' : 'Hobby',
#                 }),
#             'favourite_food' : forms.TextInput(attrs={
#                 'class' : 'form-control',
#                 'placeholder' : 'Input your favourite food or drinks',
#                 'type' : 'text',
#                 'maxlength' : '50',
#                 'required' : True,
#                 'style' : 'border:0; width:100%;text-align:center;background:black;color:white;',
#                 'label' : 'Favourite food or drinks',
#             }),
#             'class_year' : forms.TextInput(attrs={
#                 'class' : 'form-control',
#                 'placeholder' : 'Input your class year',
#                 'type' : 'Integer',
#                 'required' : True,
#                 'style' : 'border:0; width:100%;text-align:center;background:black;color:white;',
#                 'label' : 'Class Year',
#             })
#         }

homepage/views.py
from django.shortcuts import render, redirect
from .forms import input
from .models import ClassYear, Friends

# Create your views here.

def index(request):
    return render(request, 'Homepage.html')

def message(request):
    if request.method == "POST":
        form = input(request.POST)
        if (form.is_valid()):
            friend = Friends()
            year = ClassYear()
            friend.display_name = form.cleaned_data['display_name']
            friend.hobby = form.cleaned_data['hobby']
            friend.favourite_food = form.cleaned_data['favourite_food']
            friend.class_year = form.cleaned_data['class_year']
            year.class_year = form.cleaned_data['class_year']
            friend.save()
        return redirect('/message')
    else:
        form = input()
        friend = Friends.objects.all()
        year = ClassYear.objects.all()
        response = {'friend' : friend, 'year' : year, 'forms': input}
        return render(request, 'Message.html', response)

homepage/templates/Homepage.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'bigscreen.css' %}">
        
        <title>Website Ferdi Salim Sungkar</title>
    </head>
    <body>
        <div class="bg">
            <div class="one">
                <ul class="nav justify-content-center">
                    <li class="about">
                      <a class="nav-link" href="#about">about</a>
                    </li>
                    <li class="skills">
                      <a class="nav-link" href="#two">skills</a>
                    </li>
                    <li class="contact">
                        <a class="nav-link" href="#three">contact</a>
                    </li>
                    <li class="goodbye">
                        <a class="nav-link" href="{% url 'homepage:message' %}">add friends</a>
                    </li>
                </ul>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md">
                        <h1 id="top">WELCOME</h1> 
                    </div>
                    <div class="col-md-1"></div>
                </div>
            </div>
    
            <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

            <div class="two">
                <div class="row">
                    <div class="col-lg-4">
                        <img class="white-photo" src="{% static 'Images/white.jpeg' %}" alt="white">
                        <img class="my-profile-photo" src="{% static 'Images/profilephoto.jpeg' %}" alt="profile-photo">
                    </div>
                    <div class="col-lg">
                        <h2 id="about">FERDI SALIM SUNGKAR</h2>
                        <h3></h3>
                        <h3>
                            My name is Ferdi, I'm a Computer Science student
                            in University of Indonesia. I'm making this website as an assignment
                            for my Web Development and Programming class. I'm enjoying this class
                            so far and hoping to learn more about Web Development.
                        </h3>
                        <h3></h3>
                        <h3>
                            I'm into movies, when im feeling down or have nothing to do i'll usually
                            watch movies. Some of my favourite movies are Forrest Gump, Memento, and 
                            Grand Budapest Hotel.
                        </h3>
                    </div>
                </div>
                <br><br><br><br>
            </div>        
        </div>

        <div class="bg2">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md">
                        <h1 id="two">SKILLS</h1> 
                    </div>
                    <div class="col-md-1"></div>
                </div>
            </div>
    
            <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    
            <div class="two">
                <div class="container">
                    <h4></h4>
                    <div class="row">
                        <div class="col-md-12">
                            <h4>HTML</h4>
                            <br>
                            <div class="progress">
                                <div class="progress-bar w-100" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="70" style="width: 70%; color: #E3E8EA;"></div>
                            </div>
                        </div>
                    </div>
                    <h4></h4>                    
                    <h4></h4>
                    <div class="row">
                        <div class="col-md-12">
                            <h4>CSS</h4>
                            <br>
                            <div class="progress">
                                <div class="progress-bar w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 40%;"></div>
                            </div>
                        </div>
                    </div>
                    <h4></h4>
                    <h4></h4>
                    <div class="row">
                        <div class="col-md-12">
                            <h4>Java</h4>
                            <br>
                            <div class="progress">
                                <div class="progress-bar w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 40%;"></div>
                            </div>
                        </div>
                    </div>
                    <h4></h4>
                    <h4></h4>
                    <div class="row">
                        <div class="col-md-12">
                            <h4>Python</h4>
                            <br>
                            <div class="progress">
                                <div class="progress-bar w-100" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 40%;"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <br><br><br><br><br>
            </div>
        </div>

        <div class="bg3">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md">
                        <h1 id="three">CONTACT</h1> 
                    </div>
                    <div class="col-md-1"></div>
                </div>
                <br><br><br><br><br><br><br><br><br>
            </div>
            <div class="two">
                <div class="container-fluid">
                    <h5>
                        FERDI SALIM SUNGKAR           
                    </h5>
                    <h6>
                        ferdisgk@gmail.com
                    </h6>
                    <h6>
                        +62 878 8070 7645
                    </h6>
                    <br>
                    <div class="row">
                        <div class="col-sm-1">
                            <a href="https://www.instagram.com/ferdisungkar/">
                                <img alt="Instagram" src="{% static 'Images/Logo/Instagram.png' %}" height="50">
                        </div>
                        <div class="col-sm-1">
                            <a href="https://twitter.com/ferdisungkar">
                                <img class="twitter" src="{% static 'Images/Logo/twitter.png' %}" height="50">
                        </div>
                        <div class="col-sm-1">
                            <a href="https://www.linkedin.com/in/ferdi-sungkar-99760417b/">
                                <img class="linkedin" src="{% static 'Images/Logo/linkedin.png' %}" height="50">
                        </div>
                    </div>
                </div>
                <br>
            </div>
        </div>
        <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

homepage/templates/Message.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        
        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'bigscreen.css' %}">

        <title>Add Friends</title>
    </head>
    <body>
        <div class="bg">
            <div class="one">
                <ul class="nav justify-content-center">
                    <li class="home">
                        <a class="nav-link" href="{% url 'homepage:index' %}">home</a>
                    </li>
                </ul>
            </div>
            <div class="container" style="max-width: 70%; display: flex; justify-content: center; align-items: center; margin-top: 0%;">
                <div class="row-12">
                    <div class="col" style="text-align: center;">
                        <h1 style="color: white;">
                            Add yourself
                        </h1>
                    </div>
                    <form action="{% url 'homepage:message' %}" method="POST" class="col">
                        {% csrf_token %}
                        <!-- <input type="text" name="display_name" class="form-control" placeholder="Input your name" maxlength="300" required="" style="border:0; width:100%;text-align:left;background:#495054;color:white;" label="" id="id_display_name">
                        <br>
                        <input type="text" name="hobby" class="form-control" placeholder="Input your hobby" maxlength="300" required="" style="border:0; width:100%;text-align:left;background:#495054;color:white;" label="" id="id_hobby">
                        <br>
                        <input type="text" name="favourite_food" class="form-control" placeholder="Input your favourite food or drinks" maxlength="300" required="" style="border:0; width:100%;text-align:left;background:#495054;color:white;" label="" id="id_favourite_food">
                        <br>
                        <input type="number" name="class_year" class="form-control" placeholder="Input your year" maxlength="4" required="" style="border:0; width:100%;text-align:left;background:#495054;color:white;" label="" id="id_class_year"> -->
                        {{ forms }}
                        <div class="row mb-5">
                            <input type="Submit" name="button_input" class="btn btn-primary" value="add" style="margin-top : 2%;text-align: center;margin-right: auto; margin-left: auto;border-radius: 18px;">
                        </div>
                    </form>
                    <div class="col" style="color: white; margin: 0 auto 0 auto;text-align: center;overflow-y: scroll; max-height: 200px; ">
                        {% for i in friend %}
                            <p>
                                {{ i.display_name }} - {{i.hobby}} - {{i.favourite_food}} - {{i.class_year}}
                            </p>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <br><br><br><br><br>
        </div>
    </body>
    <foot style="position: absolute; top: 95%; width: 100%;">
        <p style="color: white; text-align: center;">
            <i>
                Ferdi Sungkar © 2020
            </i>
        </p>
    </foot>
</html>